### ISSUE TITLE
Motion/vibration monitoring

### ISSUE THREAD

**Issue by sned45** [craigmw/CellarWarden#1]
Reaching out to you about adding motion and vibration sensors with monitoring and alerts.

**Comment by craigmw** [comment]
Thanks for moving the discussion here. I don't know much about the kind of motion sensor you are using, but you would likely need to add an analog to digital converter to connect up the motion sensor. This app only polls the different sensors about once every three seconds or so. For motion or vibration sensing, I would think you would need a much more rapid sampling rate, unless the sensor has some form of digital output. In any event, what is the intended application?

**Comment by sned45** [comment]
Looking at making a safe monitoring sensor that would track and alert on
high or low temp, humidity, door open and motion incase someone broke into
my house and tried to open or move my safe.   Was thinking a sensor like
would work one
http://www.electrodragon.com/product/vibration-sensor-sw-18010p/ or maybe
an accelemotor  to record movement
http://www.electrodragon.com/product/triple-axis-accelerometer-breakout-adxl345/

**Comment by craigmw** [comment]
You could in theory connect the linked vibration sensor to a free GPIO pin on the RPi and set it up as a door monitor. But this would require sustained movement (greater than one minute) to trigger an alarm in CellarWarden. Programming this wouldn't be too difficult, but it's just not a sensor I see being of use for wine cellars/fermentation control at this time.

**Comment by sned45** [comment]
Yea, greater then a minute wouldn't work.  Thank you for the info and the help.

Sent via smartphone

-------- Original message --------
