### ISSUE TITLE
Compression Job

### ISSUE THREAD

**Issue by xmanofnapa** [craigmw/CellarWarden#2]
First off, great program. I'm using it to hack a window A/C for my cellar and it works great.

There are a couple of minor issues with the `runJobs` function:
1. `logCompressTime` doesn't seem to be initialized. After the server is launched (first time or after reboot), the compression job never runs. If compression is manually launched once, then the job subsequently runs.
2. If the compression job completes during the same minute that it started,  the job will not run on subsequent days, as the line  `if ( minsNow !== lastMins ) { //Prevent running compressLogFile more than once each day.`  prevents it from running ever again, not just more than once a day. 
   I'm using a Raspberry Pi 3 and so far, compression is completing in a few seconds.

Thanks.

**Comment by craigmw** [comment]
Yes, I've also experienced some times when the compress routine fails to run. I am working on this issue and hope to push a fix for this shortly. Keep your eyes open for this change on the github repository.

Great to hear you are using this to control a window A/C. In my setup, I'm using a wine cooler unit, which seems to work fine. How do you manage to fool the internal thermostat on your unit to cool below its normal range?

Thanks...

Craig

**Comment by xmanofnapa** [comment]
Good to hear.
In my setup, a little 1W resistor with a foil wrapper around it and the window A/C temperature sensor works great.

**Comment by craigmw** [comment]
Brilliant!

**Comment by craigmw** [comment]
I've updated the automated logfile compression routine. Instead of using my own code for this, I've incorporated a node.js version of cron to run jobs at specified times. This appears to work, but you should check it to see if it works on your end. To update, go to your CellarW directory (e.g. /home/pi/CellarW) and type:

git pull
npm update
reboot

This should institute the new changes. 

BTW, I would love to see a writeup (with pictures!) of your setup. Maybe you could post this on winebeserkers.com or cellartracker.com. 

Cheers...

Craig

**Comment by xmanofnapa** [comment]
I've updated and successfully ran a few simple tests. The job runs as expected after cold boot. I'll watch it over next few days, but it should work fine with cron now.

I'll try to do a write-up or at least post pictures of my setup soon. I'm in the process of making the controller more permanent, moving it from a breadboard to a PCB in a small(-ish) enclosure, if I can find the right one.

Thanks.

**Comment by craigmw** [comment]
Good to hear it's working. If I can find time, I intend to release an RPi hat for CellarWarden easier to set up. I'm not sure when this will be though, as I'm still working on some hardware ideas.

**Comment by xmanofnapa** [comment]
The job has been running solidly with the new routine. Closing the issue. 
Thanks.

**Comment by craigmw** [comment]
Great to hear!
