### ISSUE TITLE
Reject Extreme

### ISSUE THREAD

**Issue by xmanofnapa** [craigmw/CellarWarden#3]
Craig, 
I updated to the new version this morning and am getting the following error:
`Thu Oct 13 2016 14:50:33 GMT-0700 (PDT): ERROR: Caught exception in CellarWarden: TypeError: sensors.rejectExtremes is not a function`
when the option is enabled.

That seems to be messing up both logging and controller functionalities.

Disabling the 'Reject Extremes' option and rebooting seem to restore proper logging and controlling, but since one of my sensors is giving me a 4 digit reading every other day, the option is important (to me, at least :-) )

(BTW, I had increased the threshold to 100 on my build, in `config.html`. It was rejecting a bunch of good readings because the 'old values' were resetting to 0.  Since bad readings are in the 1000's, it might be good to increase the max too)

Thanks

**Comment by craigmw** [comment]
Thank you for pointing out this error. I'm in the process of updating the daemon's architecture to ease the inclusion of new sensor types. When I moved the sensors and logging routines out of the main file (CellarW.js), there were some variables that were not adequately defined in those new files. This resulted in a couple of errors. These should now be fixed, so go ahead and use git pull and reboot to correct these. Let me know if you encounter any other problems.

**Comment by xmanofnapa** [comment]
Updated and no more errors.

Thanks.

**Comment by craigmw** [comment]
Xman:

I also updated config.html to increase the reject threshold max to 100. Thanks for the tip.

**Comment by craigmw** [comment]
Xman:

I noted a few errors with threshold detection after a recent architecture change, so I've just updated this repository. I suggest a git pull to address this.
