### ISSUE TITLE
Javascript errors and broken links?

### ISSUE THREAD

**Issue by iverberk** [craigmw/CellarWarden#5]
Hi,

I just tried to install CellarWarden on my RPi. The installation went smoothly but upon opening the application I run into a lot of errors and non-functional links. I've created screenshots to clarify:

http://pasteboard.co/34v32yzAg.png
http://pasteboard.co/j39L3ZlR.png

Mind you, I have not attached any sensors yet. This is just the RPI with no peripherals yet.

Any suggestions what to do here? Seems like a very nice project which I really would like to use. Do you also actively maintain it or is it a 'dead' project? Just wondering before I invest a lot of time/effort into using it :-)

**Comment by craigmw** [comment]
Ivo:

Yes, CellarWarden is being actively maintained. I just uploaded some updates last week to Github.

I'm not sure what the issue is, but it appears to be some problem with your browser. It appears that the browser is connecting to the CellarWarden daemon running on your RPi, but that there seems to be some problem with the browser running jQuery. Have you tried this on a different browser to see if there might be an incompatibility? It looks like you are using the Edge browser, which I use on my desktop with success. However, I don't have a bunch of third party plugins, so maybe there might be some contention? In any event, try this from another browser (e.g. a smartphone or some other device) and let me know if you are still having issues.

Cheers...

Craig

**Comment by craigmw** [comment]
Incidentally, you don't need to connect any sensors to test out CellarWarden. It will just report zero values.

**Comment by iverberk** [comment]
Ah ok, great to hear that you are maintaining it! :-)

I'm on MacOS (Sierra) and I've tried it with Chrome (the screenshots), Safari and Firefox. They all give me the same problems. I'm unable to try it with IE but surely it must work on the other browsers?

Tried it on my iPhone too, same problems...

Any suggestions on what I can do to debug this? I can give you browser versions but since I have trouble on all of them I don't think it is version related. I followed the installation guide in the readme without any trouble.

**Comment by craigmw** [comment]
Ivo:

Can you provide a screenshot of what the browser looks like without the console shown? Do you see the main graph screen (i.e. without using the Inspect Element window)?

Craig

**Comment by craigmw** [comment]
I get some of those errors too (just due to a lag between the server and the browser), but the connection should still work. You should just ignore the errors.

**Comment by iverberk** [comment]
Hi Craig,

I see the main graph screen (http://pasteboard.co/362EIbrR0.png). The only big problem I run into is the 404 error when I click the controllers link (it's trying to load controllers.js but isn't able to find it, see the screenshot for the exact error). It doesn't show the configuration page. This also happens in all browsers and on all the links except help.

Ivo

**Comment by craigmw** [comment]
Ah, I think I know what's going on. I moved the javascript out of the HTML files recently, and it appears that I didn't upload those new javascript files onto the GitHub repository. So, when you click on Configure, Alarms or Controllers buttons, nothing will happen (except another error will be sent to the console). I'm not quite sure how those files didn't get uploaded, but I'll do so later today. You should then be able to use git pull to update your system.

Sorry about that!

**Comment by iverberk** [comment]
Great, glad you found the problem! I'll try again when the files are there. Thanks!

**Comment by craigmw** [comment]
Ivo:

I've uploaded the missing javascript files. 

To update:

cd /home/pi/CellarW
git pull

Try it again and let me know if it works.

**Comment by iverberk** [comment]
It works! Thanks for the quick resolve and looking forward to using it.

**Comment by craigmw** [comment]
Great! Sorry about that. I appreciate you catching this issue. Let me know how it works for you once you get it up and running.

Cheers...

Craig
