### ISSUE TITLE
limit on temperature?

### ISSUE THREAD

**Issue by iverberk** [craigmw/CellarWarden#8]
Hi Craig,

Is it possible to set hard limits on the allowed temperature? I'm using a freezer box and I do not want the temperature to go below zero degrees at all times. Normally this won't happen if the algorithm works properly but in case the output gets stuck or some other kind of malfunction it would be nice if CellerWarden just turns off the actuator if it comes above/below a certain threshold.

**Comment by craigmw** [comment]
CellarWarden shouldn't become stuck in normal operation, but there is a chance that things might go haywire and cause this to occur. This could come about by a crash in CellarWarden, although this should simply cause CellarWarden to restart. I think this is an interesting feature to add, perhaps under the Alarm functionality (or in the Controllers)? I can also imagine that the RPi itself is crashed, in which case a reboot would hopefully recover functionality. I would suggest adding a Watchdog Timer to address this. I'm currently working on a latching hardware timer that will reboot the RPi and shut down any associated actuators if CellarWarden fails to send it a periodic watchdog signal.
